from setuptools import setup, find_packages

setup(
    name="protein-sssl-operator",
    version="0.1.0",
    description="Self-Supervised Structure-Sequence Learning with Neural Operators for Protein Folding",
    author="Daniel Schmidt",
    author_email="daniel@terragonlabs.ai",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0.0",
        "torchvision",
        "numpy>=1.21.0",
        "scipy",
        "pandas",
        "scikit-learn",
        "biopython",
        "einops",
        "transformers>=4.20.0",
        "datasets",
        "wandb",
        "matplotlib",
        "seaborn",
        "tqdm",
        "omegaconf",
        "hydra-core",
        "biotite",
        "py3Dmol",
    ],
    extras_require={
        "md_tools": [
            "mdtraj",
            "openmm",
            "pdbfixer",
        ],
        "dev": [
            "pytest",
            "pytest-cov",
            "black",
            "isort",
            "flake8",
            "mypy",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)