# Horizontal Pod Autoscaler for protein-sssl-operator
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: protein-sssl-hpa
  namespace: protein-sssl
  labels:
    app.kubernetes.io/name: protein-sssl
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: protein-sssl-inference
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: inference_requests_per_second
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60

---
# Vertical Pod Autoscaler for resource optimization
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: protein-sssl-vpa
  namespace: protein-sssl
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: protein-sssl-training
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: protein-sssl
      minAllowed:
        cpu: 100m
        memory: 512Mi
      maxAllowed:
        cpu: 8
        memory: 32Gi
      mode: Auto

---
# Custom Resource for GPU autoscaling
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-autoscaling-config
  namespace: protein-sssl
data:
  config.yaml: |
    gpu_scaling:
      enabled: true
      metrics:
        - name: gpu_utilization
          threshold: 80
        - name: gpu_memory_utilization
          threshold: 85
      scale_up:
        threshold: 80
        cooldown_seconds: 300
      scale_down:
        threshold: 20
        cooldown_seconds: 600
      min_replicas: 1
      max_replicas: 5